site_name: Gaming Checklists
repo_url: https://github.com/Vytez/gamingchecklists
remote_branch: gh-pages
edit_uri: blob/main/docs/
theme:
    name: null
    custom_dir: cinder
    disable_nav_previous_next: true
    disable_footer: true
markdown_extensions:
    - markdown_checklists.extension
    - pymdownx.tilde
extra_css:
    - "css/custom.css"
extra_javascript:
    - "js/checkbox_localstorage.js"
nav:
    - Home: index.md
    - Games:
        - Mass Effect 3: checklists/mass_effect_3/index.md
        - Tales of Vesperia: checklists/tales_of_vesperia/index.md