site_name: Gaming Checklists
remote_branch: gh-pages
theme:
    name: readthedocs
    custom_dir: theme_customization
markdown_extensions:
    - markdown_checklists.extension
    - pymdownx.tilde
extra_css:
    - custom.css
extra_javascript:
    - checkbox_cookie.js
nav:
    - Home: index.md
    - Games:
        - Mass Effect 3: checklists/mass_effect_3/index.md
        - Tales of Vesperia: checklists/tales_of_vesperia/index.md