site_name: Gaming Checklists
remote_branch: gh-pages
theme:
    name: readthedocs
    custom_dir: theme_customization
markdown_extensions:
    - markdown_checklists.extension
    - pymdownx.tilde
extra_css:
    - custom.css
extra_javascript:
    - checkbox_cookie.js
nav:
    - Home: index.md
    - Games:
        - Tales of Vesperia: checklists/tales_of_vesperia/index.md